name: Companion Module Template
on:
  workflow_call:
    inputs:
      tagName:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  build-dispatch:
    name: Dispatch Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dispatch build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          MODULE_NAME=$(node -e "console.log(require('./package.json').name.replace(/^(@companion-module\/)/,\"\"))")
          TAG_NAME=${{ inputs.tagName }}
          echo "Running for ${MODULE_NAME}@${TAG_NAME}"
          gh workflow run -R bitfocus/companion-module-publisher do-publish.yaml -f moduleName=$MODULE_NAME -f tag=$TAG_NAME
      
      - name: Wait for completion
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          MODULE_NAME=$(node -e "console.log(require('./package.json').name.replace(/^(@companion-module\/)/,\"\"))")
          TAG_NAME=${{ inputs.tagName }}

          npx zx https://raw.githubusercontent.com/bitfocus/companion-module-publisher/main/find-run-id.mjs $MODULE_NAME $TAG_NAME
          gh run watch --exit-status --interval 10 $(cat RUN_ID)
        